@baseUrl = http://localhost:3333
@authToken = {{authenticated.response.body.access_token}}

# @name create_accounts
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Silvanei Martins",
    "email": "oi1@silvaneimartins.com.br",
    "password": "123456"
}

###

# @name authenticated
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "oi1@silvaneimartins.com.br",
    "password": "123456"
}

###

# @name create_questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Terceira Pergunta",
    "content": "Conteúdo da terceira pergunta"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}