version: "3.0"

services:
    postgres:
        container_name: nest-service-management
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: service-management
            PGDATA: /data/postgres
        volumes:
            - ./data/pg:/data/postgres